---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update-cache: yes

  - name: install apache2 and php  package
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
