---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    apt:
      update-cache: yes
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
