---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates for  ubuntu servers
    apt:
      upgrade: dist
      update-cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:
  -  name: install php and apache for ubuntu servers
     apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
     when: ansible_distribution == "Ubuntu"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest


